// Exercise names in Spanish (rioplatense gym usage). Hand-authored, keyed by exercise id.
// Coverage is checked by scripts/check-exercise-names.mjs; corrections come from
// docs/exercise-names-es-review.csv. Any id missing here falls back to the English name.
export default {
  "0001": "abdominal 3/4",
  "0002": "flexión lateral de tronco a 45°",
  "0003": "bicicleta en el aire",
  "1512": "estiramiento de cuádriceps en cuatro apoyos",
  "0006": "toques de talón alternados",
  "0007": "jalón al pecho lateral alternado",
  "1368": "movimiento circular de tobillo",
  "3293": "dominada archer",
  "3294": "flexión archer",
  "2355": "balanceo de piernas colgado con rodillas flexionadas",
  "2333": "balanceo de piernas colgado con piernas rectas",
  "3214": "toque de punta de pie con brazos abiertos en círculo",
  "3204": "abdominal completo con brazos por encima de la cabeza",
  "0009": "fondo de pecho asistido (de rodillas)",
  "0011": "elevación de rodillas colgado asistida",
  "0010": "elevación de rodillas colgado asistida con impulso",
  "1708": "estiramiento de gemelos acostado asistido",
  "1709": "estiramiento de glúteos acostado asistido",
  "1710": "estiramiento de glúteo y piriforme acostado asistido",
  "0012": "elevación de piernas acostado asistida con impulso lateral",
  "0013": "elevación de piernas acostado asistida con impulso",
  "0014": "giro ruso asistido",
  "0015": "dominada asistida con agarre cerrado paralelo",
  "0016": "femoral boca abajo asistido",
  "1713": "estiramiento de cuádriceps boca abajo asistido",
  "1714": "estiramiento de recto femoral boca abajo asistido",
  "0017": "dominada asistida",
  "1716": "estiramiento de pectoral mayor sentado asistido con pelota suiza",
  "1712": "estiramiento de aductores de costado asistido",
  "1758": "abdominal asistido",
  "1431": "dominada supina de pie asistida",
  "1432": "dominada de pie asistida",
  "0018": "extensión de tríceps de pie asistida (con toalla)",
  "0019": "fondo de tríceps asistido (de rodillas)",
  "2364": "fondo de pecho asistido con agarre abierto (de rodillas)",
  "3220": "saltos con piernas abiertas y cerradas",
  "3672": "paso adelante y atrás",
  "1314": "extensión de espalda sobre pelota suiza",
  "3297": "palanca dorsal (back lever)",
  "1405": "estiramiento de pectoral por detrás",
  "1473": "salto hacia atrás",
  "0020": "tabla de equilibrio",
  "0968": "curl de bíceps alternado con banda",
  "0969": "v-up alternado con banda",
  "0970": "dominada asistida con banda",
  "0971": "rueda abdominal asistida con banda",
  "1254": "press de banca con banda",
  "0980": "extensión de cadera con torso inclinado con banda",
  "0972": "crunch bicicleta con banda",
  "0974": "jalón con agarre cerrado con banda",
  "0975": "flexión con agarre cerrado con banda",
  "0976": "curl concentrado con banda",
  "3117": "jalón con agarre cerrado y espalda fija con banda",
  "3116": "jalón con agarre supino y espalda fija con banda",
  "0977": "elevación lateral al frente con banda",
  "0978": "elevación frontal con banda",
  "1408": "elevación de cadera con banda",
  "0979": "press pallof horizontal con banda",
  "0981": "abdominal jack knife con banda",
  "0983": "jalón a un brazo de rodillas con banda",
  "0985": "crunch con giro de rodillas con banda",
  "0984": "rotación interna de cadera acostado con banda",
  "1002": "elevación de pierna recta acostado con banda",
  "0986": "curl de bíceps a un brazo por encima de la cabeza con banda",
  "0987": "sentadilla búlgara a un brazo y una pierna con banda",
  "0988": "remo bajo a un brazo de pie con banda",
  "0989": "press de pecho a un brazo con giro con banda",
  "0990": "remo sentado a un brazo con giro con banda",
  "0991": "pull through con banda",
  "0992": "abdominal con empuje con banda",
  "0993": "apertura posterior con banda",
  "0994": "curl invertido de muñeca con banda",
  "0996": "rotación interna de cadera sentado con banda",
  "1011": "giro sentado con banda",
  "0997": "press de hombros con banda",
  "1018": "encogimiento de hombros con banda",
  "0998": "extensión lateral de tríceps con banda",
  "0999": "elevación de gemelo a una pierna con banda",
  "1000": "elevación invertida de gemelo a una pierna con banda",
  "1001": "sentadilla búlgara a una pierna con banda",
  "1004": "sentadilla con banda",
  "1003": "sentadilla con remo con banda",
  "1005": "crunch de pie con banda",
  "1022": "remo para deltoides posterior de pie con banda",
  "1007": "crunch de pie con giro con banda",
  "1008": "subida al cajón con banda",
  "1009": "peso muerto con piernas rígidas con banda",
  "1023": "peso muerto con piernas rígidas y espalda recta con banda",
  "1010": "peso muerto con piernas rectas con banda",
  "1012": "press por encima de la cabeza con giro con banda",
  "1369": "elevación de gemelos a dos piernas con banda (banda bajo ambas piernas) (v. 2)",
  "1013": "jalón con agarre supino con banda",
  "1014": "v-up con banda",
  "1015": "press pallof vertical con banda",
  "1016": "curl de muñeca con banda",
  "1017": "elevación en Y con banda",
  "0023": "curl de bíceps alternado con barra",
  "0024": "sentadilla frontal en banco con barra",
  "0025": "press de banca con barra",
  "0026": "sentadilla en banco con barra",
  "1316": "pullover con brazos flexionados con barra",
  "0027": "remo con torso inclinado con barra",
  "2407": "curl de bíceps con barra (con arm blaster)",
  "0028": "cargada y press con barra",
  "0029": "sentadilla frontal con agarre de cargada con barra",
  "0030": "press de banca con agarre cerrado con barra",
  "0031": "curl de bíceps con barra",
  "0032": "peso muerto con barra",
  "0033": "press de banca declinado con barra",
  "0034": "pullover declinado con brazos flexionados con barra",
  "0035": "press declinado con agarre cerrado hacia la frente con barra",
  "1255": "pullover declinado con barra",
  "0036": "press declinado con agarre abierto con barra",
  "0037": "pullover declinado con agarre abierto con barra",
  "0038": "curl drag con barra",
  "1370": "elevación de gemelos en el piso con barra",
  "0039": "sentadilla frontal al pecho con barra",
  "0041": "elevación frontal con barra",
  "0040": "elevación frontal y pullover con barra",
  "0042": "sentadilla frontal con barra",
  "0043": "sentadilla profunda con barra",
  "1461": "sentadilla profunda con barra (vista posterior)",
  "1462": "sentadilla profunda con barra (vista lateral)",
  "1545": "sentadilla zercher profunda con barra",
  "1409": "puente de glúteos con barra",
  "3562": "puente de glúteos con ambas piernas en banco con barra",
  "0044": "buenos días con barra",
  "0045": "press de banca guillotina con barra",
  "0046": "hack squat con barra",
  "1436": "sentadilla con barra alta",
  "0047": "press de banca inclinado con barra",
  "1719": "press de banca inclinado con agarre cerrado con barra",
  "0048": "press inclinado con agarre invertido con barra",
  "0049": "remo inclinado con barra",
  "0050": "elevación de hombros inclinado con barra",
  "0051": "sentadilla jefferson con barra",
  "0052": "press de banca JM con barra",
  "0053": "sentadilla con salto con barra",
  "1410": "zancada lateral con barra",
  "1435": "sentadilla con barra baja",
  "0054": "zancada con barra",
  "1720": "extensión de tríceps tras nuca acostado con barra",
  "0055": "press acostado con agarre cerrado con barra",
  "0056": "extensión de tríceps acostado con agarre cerrado con barra",
  "0057": "extensión acostado con barra",
  "0058": "elevación acostado sobre la cadera con barra",
  "0059": "curl predicador acostado con barra",
  "0061": "extensión de tríceps acostado con barra",
  "0060": "extensión de tríceps acostado tipo rompecráneos con barra",
  "0063": "sentadilla con pies juntos con barra",
  "0064": "remo con torso inclinado a un brazo con barra",
  "0065": "press en el piso a un brazo con barra",
  "0066": "peso muerto lateral a un brazo con barra",
  "0067": "arranque a un brazo con barra",
  "0068": "sentadilla a una pierna con barra",
  "0069": "sentadilla por encima de la cabeza con barra",
  "1411": "curl de muñeca con palmas abajo sobre un banco con barra",
  "1412": "curl de muñeca con palmas arriba sobre un banco con barra",
  "3017": "remo pendlay con barra",
  "1751": "press desde pines con barra",
  "0070": "curl predicador con barra",
  "0071": "abdominal con press con barra",
  "0072": "curl inclinado boca abajo con barra",
  "0073": "pullover con barra",
  "0022": "pullover al press con barra",
  "0074": "rack pull con barra",
  "0075": "elevación de deltoides posterior con barra",
  "0076": "remo para deltoides posterior con barra",
  "0078": "zancada hacia atrás con barra",
  "0077": "zancada hacia atrás con barra (v. 2)",
  "0079": "curl invertido de muñeca con barra (v. 2)",
  "2187": "press de banca con agarre cerrado invertido con barra",
  "0080": "curl invertido con barra",
  "0118": "remo con torso inclinado con agarre invertido con barra",
  "1256": "press de banca declinado con agarre invertido con barra",
  "1257": "press de banca inclinado con agarre invertido con barra",
  "1317": "remo en banco inclinado con agarre invertido con barra",
  "1721": "rompecráneos con agarre invertido con barra",
  "0081": "curl predicador invertido con barra",
  "0082": "curl invertido de muñeca con barra",
  "0084": "rueda abdominal con barra",
  "0083": "rueda abdominal desde el banco con barra",
  "0085": "peso muerto rumano con barra",
  "0086": "press militar tras nuca sentado con barra",
  "0087": "press bradford sentado con barra",
  "0088": "elevación de gemelos sentado con barra",
  "1371": "elevación de gemelos sentado con barra",
  "1718": "extensión de tríceps tras nuca sentado con agarre cerrado con barra",
  "0089": "curl concentrado sentado con agarre cerrado con barra",
  "0090": "buenos días sentado con barra",
  "0091": "press por encima de la cabeza sentado con barra",
  "0092": "extensión de tríceps por encima de la cabeza sentado con barra",
  "0094": "giro sentado con barra",
  "0095": "encogimiento de hombros con barra",
  "0096": "flexión lateral de tronco con barra (v. 2)",
  "0098": "sentadilla búlgara lateral con barra",
  "0097": "sentadilla búlgara lateral con barra (v. 2)",
  "1756": "peso muerto a una pierna con barra",
  "0099": "sentadilla búlgara a una pierna con barra",
  "2799": "elevación de piernas alternada sentado con barra",
  "2800": "elevación de piernas alternada sentado con barra",
  "0100": "esquiador con barra",
  "0101": "sentadilla de velocidad con barra",
  "2810": "sentadilla búlgara con barra (v. 2)",
  "0102": "sentadilla de rodillas con barra",
  "2798": "sentadilla con salto y zancada hacia atrás con barra",
  "0103": "rueda abdominal de pie con barra",
  "0104": "curl de muñeca por detrás de pie con barra",
  "0105": "press bradford de pie con barra",
  "1372": "elevación de gemelos de pie con barra",
  "0106": "curl de pie con agarre cerrado con barra",
  "1456": "press militar de pie con agarre cerrado con barra",
  "2414": "curl concentrado de pie con barra",
  "0107": "elevación frontal por encima de la cabeza de pie con barra",
  "0108": "elevación de gemelos de pie con barra",
  "0109": "extensión de tríceps por encima de la cabeza de pie con barra",
  "0110": "curl con agarre invertido de pie con barra",
  "0111": "elevación de gemelos con balanceo de pie con barra",
  "0112": "giro de pie con barra",
  "1629": "curl de bíceps con agarre abierto de pie con barra",
  "1457": "press militar de pie con agarre abierto con barra",
  "0113": "curl de pie con agarre abierto con barra",
  "0114": "subida al cajón con barra",
  "0115": "buenos días con piernas rígidas con barra",
  "0116": "peso muerto con piernas rectas con barra",
  "0117": "peso muerto sumo con barra",
  "3305": "thruster con barra",
  "0120": "remo al mentón con barra",
  "0119": "remo al mentón con barra (v. 2)",
  "0121": "remo al mentón con barra (v. 3)",
  "0122": "press de banca con agarre abierto con barra",
  "1258": "press de banca con agarre invertido abierto con barra",
  "0124": "sentadilla con pies bien separados con barra",
  "0123": "remo al mentón con agarre abierto con barra",
  "0126": "curl de muñeca con barra",
  "0125": "curl de muñeca con barra (v. 2)",
  "0127": "sentadilla zercher con barra",
  "3212": "toque de punta de pie básico",
  "0128": "cuerdas de batalla",
  "3360": "caminata del oso",
  "1259": "estiramiento de pecho tras nuca",
  "0129": "fondo en banco (rodillas flexionadas)",
  "1399": "fondo en banco con pies en el piso",
  "0130": "extensión de cadera en banco",
  "3019": "dominadas en banco",
  "3639": "giro acostado con rodillas flexionadas",
  "1770": "curl concentrado con la pierna en el bíceps",
  "0139": "dominadas cerradas para bíceps",
  "0140": "dominada para bíceps",
  "0137": "body-up",
  "3543": "sentadilla con salto en caída con peso corporal",
  "3544": "plancha lateral inclinada con peso corporal",
  "1771": "extensión de tríceps de rodillas con peso corporal",
  "1769": "curl de bíceps de costado con peso corporal",
  "3168": "remo en sentadilla con peso corporal",
  "3167": "remo en sentadilla con peso corporal (con toalla)",
  "1373": "elevación de gemelos de pie con peso corporal",
  "3156": "remo a un brazo de pie con agarre cerrado con peso corporal",
  "3158": "remo de pie con agarre cerrado con peso corporal",
  "3162": "remo a un brazo de pie con peso corporal",
  "3161": "remo a un brazo de pie con peso corporal (con toalla)",
  "3166": "remo de pie con peso corporal",
  "3165": "remo de pie con peso corporal (con toalla)",
  "0138": "bottoms-up",
  "1374": "salto al cajón hacia abajo con estabilización a una pierna",
  "2466": "puente con escalador (cruzado)",
  "1160": "burpee",
  "0870": "elevación de glúteos",
  "1494": "postura de yoga de la mariposa",
  "0148": "press de hombros alternado en polea",
  "0149": "extensión de tríceps alternada en polea",
  "3235": "curl femoral invertido asistido en polea",
  "0150": "jalón al pecho con barra en polea",
  "0151": "press de banca en polea",
  "1630": "curl con agarre cerrado en polea",
  "1631": "curl concentrado en polea",
  "0152": "extensión concentrada en polea (sobre la rodilla)",
  "0153": "jalón al pecho cruzado en polea",
  "0154": "apertura posterior cruzada en polea",
  "0155": "cruce de poleas (variante)",
  "0868": "curl en polea",
  "0157": "peso muerto en polea",
  "0158": "apertura declinada en polea",
  "1260": "press declinado a un brazo en polea",
  "1261": "press declinado en polea",
  "0159": "remo sentado declinado con agarre abierto en polea",
  "1632": "curl drag en polea",
  "0160": "remo sentado en el piso con agarre abierto en polea",
  "0161": "elevación al frente en polea",
  "0162": "elevación frontal en polea",
  "0164": "elevación frontal de hombros en polea",
  "0165": "curl martillo en polea (con soga)",
  "1722": "extensión de tríceps por encima de la cabeza en polea alta",
  "0167": "remo alto en polea (de rodillas)",
  "0168": "aducción de cadera en polea",
  "0169": "press de banca inclinado en polea",
  "1318": "remo en banco inclinado en polea",
  "0171": "apertura inclinada en polea",
  "0170": "apertura inclinada en polea (sobre pelota suiza)",
  "0172": "extensión de tríceps inclinada hacia abajo en polea",
  "0173": "extensión de tríceps inclinada en polea",
  "0174": "giro tipo judo en polea",
  "0860": "patada de tríceps en polea",
  "0175": "crunch de rodillas en polea",
  "3697": "remo para deltoides posterior de rodillas en polea (con soga)",
  "0176": "extensión de tríceps de rodillas en polea",
  "2330": "jalón al pecho en polea con recorrido completo",
  "0177": "jalón al pecho en polea (con soga)",
  "2616": "jalón al pecho en polea con barra en V",
  "0178": "elevación lateral en polea",
  "0179": "apertura baja en polea",
  "0180": "remo bajo sentado en polea",
  "1634": "curl de bíceps acostado en polea",
  "0182": "curl acostado con agarre cerrado en polea",
  "0184": "pullover con extensión acostado en polea (con soga)",
  "0185": "apertura acostado en polea",
  "0186": "extensión de tríceps acostado en polea (v. 2)",
  "0188": "apertura media en polea",
  "0189": "remo con torso inclinado a un brazo en polea",
  "0190": "curl a un brazo en polea",
  "1262": "apertura de pecho declinada a un brazo en polea",
  "1263": "apertura a un brazo sobre pelota suiza en polea",
  "1264": "apertura inclinada a un brazo sobre pelota suiza en polea",
  "1265": "press inclinado a un brazo en polea",
  "1266": "press inclinado a un brazo sobre pelota suiza en polea",
  "0191": "inclinación lateral a un brazo en polea",
  "0192": "elevación lateral a un brazo en polea",
  "1633": "curl predicador a un brazo en polea",
  "1267": "press a un brazo sobre pelota suiza en polea",
  "3563": "jalón a un brazo en polea",
  "1635": "curl predicador invertido a un brazo en polea",
  "0193": "remo alto a un brazo con espalda recta en polea (de rodillas)",
  "1723": "extensión de tríceps a un brazo hacia abajo en polea",
  "1636": "curl por encima de la cabeza en polea",
  "1637": "curl por encima de la cabeza sobre pelota suiza en polea",
  "0194": "extensión de tríceps por encima de la cabeza en polea (con soga)",
  "1319": "remo con rotación de muñeca en polea",
  "0195": "curl predicador en polea",
  "1268": "press sobre pelota suiza en polea",
  "0196": "pull through en polea (con soga)",
  "0198": "jalón en polea",
  "0197": "jalón en polea (barra ancha)",
  "1638": "curl de bíceps en jalón de polea",
  "0201": "extensión de tríceps hacia abajo en polea",
  "0199": "extensión de tríceps hacia abajo con brazo recto en polea (v. 2)",
  "0200": "extensión de tríceps hacia abajo en polea (con soga)",
  "0202": "remo para deltoides posterior en polea (estribos)",
  "0203": "remo para deltoides posterior en polea (con soga)",
  "0204": "empuje posterior en polea",
  "0205": "jalón posterior en polea",
  "0873": "crunch invertido en polea",
  "0206": "curl invertido en polea",
  "2406": "extensión de tríceps hacia abajo con agarre invertido en polea (barra SZ) (con arm blaster)",
  "1413": "curl invertido a un brazo en polea",
  "0209": "curl predicador invertido en polea",
  "0210": "curl invertido de muñeca en polea",
  "0207": "extensión de tríceps hacia abajo con agarre invertido en polea",
  "0208": "remo alto sentado con agarre invertido y espalda recta en polea",
  "1320": "remo sentado con soga cruzada en polea",
  "1321": "remo sentado elevado con soga en polea",
  "1322": "remo en banco inclinado con extensión de soga en polea",
  "1639": "curl predicador martillo con soga en polea",
  "1724": "extensión de tríceps por encima de la cabeza con soga en polea alta",
  "1725": "extensión de tríceps inclinada con soga en polea",
  "1726": "extensión de tríceps acostado en el piso con soga en polea",
  "1640": "curl predicador martillo a un brazo con soga en polea",
  "1323": "remo sentado con soga en polea",
  "0211": "giros rusos en polea (sobre pelota suiza)",
  "2144": "press de pecho sentado en polea",
  "0212": "crunch sentado en polea",
  "1641": "curl sentado en polea",
  "0213": "remo alto sentado en polea (barra en V)",
  "0214": "remo alternado a un brazo sentado en polea",
  "1642": "curl concentrado a un brazo sentado en polea",
  "1643": "curl por encima de la cabeza sentado en polea",
  "0215": "elevación posterior sentado en polea",
  "0861": "remo sentado en polea",
  "0216": "rotación interna de hombro sentado en polea",
  "2399": "giro sentado en polea",
  "0218": "remo sentado con agarre abierto en polea",
  "0219": "press de hombros en polea",
  "0220": "encogimiento de hombros en polea",
  "0222": "flexión lateral de tronco en polea",
  "0221": "crunch de flexión lateral en polea (bosu)",
  "0223": "crunch lateral en polea",
  "1717": "sentadilla con remo en polea (con soga)",
  "1644": "curl en sentadilla en polea",
  "0224": "curl de muñeca por detrás de pie en polea",
  "1375": "elevación de gemelos de pie en polea",
  "0225": "apertura posterior alta cruzada de pie en polea",
  "0226": "crunch de pie en polea",
  "0874": "crunch de pie en polea (con soga)",
  "0227": "apertura de pie en polea",
  "0228": "extensión de cadera de pie en polea",
  "0229": "curl interno de pie en polea",
  "0230": "elevación de pie en polea",
  "0231": "extensión de tríceps a un brazo de pie en polea",
  "1376": "elevación de gemelos a una pierna de pie en polea",
  "0232": "jalón de pie en polea (con soga)",
  "0233": "remo para deltoides posterior de pie en polea (con soga)",
  "1727": "extensión de tríceps por encima de la cabeza a un brazo con agarre invertido de pie en polea",
  "0234": "remo de pie en polea (barra en V)",
  "0235": "rotación externa de hombro de pie en polea",
  "0236": "remo con giro de pie en polea (barra en V)",
  "1269": "cruces de pie erguido en polea",
  "0238": "jalón con brazo recto en polea",
  "0237": "jalón con brazo recto en polea (con soga)",
  "0239": "remo sentado con espalda recta en polea",
  "0240": "apertura posterior boca arriba en polea",
  "2464": "remo kayak thibaudeau en polea",
  "0241": "extensión de tríceps hacia abajo en polea (barra en V)",
  "2405": "extensión de tríceps hacia abajo en polea (barra en V) (con arm blaster)",
  "0242": "crunch invertido con rodillas al pecho en polea",
  "0243": "giro en polea",
  "0862": "giro en polea (arriba y abajo)",
  "0244": "jalón con giro en polea",
  "1645": "curl a dos brazos en banco inclinado en polea",
  "1728": "patada de tríceps a dos brazos en polea",
  "0245": "jalón con agarre supino en polea",
  "1270": "cruces para pecho alto en polea",
  "1324": "remo alto en polea",
  "0246": "remo al mentón en polea",
  "1325": "jalón posterior tras nuca con agarre abierto en polea",
  "0247": "curl de muñeca en polea",
  "1407": "estiramiento de gemelos con las manos en la pared",
  "1377": "estiramiento de gemelos con las manos en la pared",
  "1378": "estiramiento de gemelos con soga",
  "0248": "remo acostado con barra curva",
  "2963": "elevación de piernas rectas en silla romana",
  "1548": "estiramiento de pierna extendida en silla",
  "1271": "estiramiento de pecho y parte anterior del hombro",
  "0251": "fondo de pecho",
  "1430": "fondo de pecho (en jaula de dominadas)",
  "2462": "fondo de pecho en barra recta",
  "1272": "estiramiento de pecho con pelota suiza",
  "3216": "flexión con toque al pecho",
  "1326": "dominada supina",
  "0253": "dominadas supinas (agarre paralelo cerrado)",
  "0257": "estiramiento de rodilla en círculos",
  "1273": "flexión con palmada",
  "0258": "flexión del reloj",
  "1327": "dominada supina con agarre cerrado",
  "0259": "flexión con agarre cerrado",
  "2398": "flexión con agarre cerrado (de rodillas)",
  "0260": "cocoons",
  "1468": "toque de punta de pie con giro tipo cangrejo",
  "0262": "crunch cruzado",
  "0267": "crunch (manos por encima de la cabeza)",
  "0271": "crunch (sobre pelota suiza)",
  "0272": "crunch (sobre pelota suiza, brazos rectos)",
  "0274": "crunch en el piso",
  "3016": "curl-up",
  "3769": "sentadilla curtsy",
  "2331": "elíptica",
  "0276": "dead bug",
  "0277": "crunch declinado",
  "0279": "flexión declinada",
  "0282": "abdominal declinado",
  "1274": "flexión profunda",
  "0283": "flexión diamante",
  "0284": "elevación de gemelos tipo burro",
  "1275": "flexión en caída",
  "0285": "curl de bíceps alternado con mancuernas",
  "2403": "curl de bíceps alternado con mancuernas (con arm blaster)",
  "1646": "curl predicador martillo alternado con mancuernas",
  "1647": "curl predicador alternado con mancuernas",
  "1648": "curl martillo alternado sentado con mancuernas",
  "0286": "press lateral alternado con mancuernas",
  "1649": "curl de bíceps alternado con pierna elevada sobre pelota suiza con mancuernas",
  "1650": "curl de bíceps alternado sentado sobre pelota suiza con mancuernas",
  "2137": "press arnold con mancuernas",
  "0287": "press arnold con mancuernas (v. 2)",
  "0288": "pullover circular con mancuerna",
  "0289": "press de banca con mancuernas",
  "0290": "press sentado en banco con mancuernas",
  "0291": "sentadilla en banco con mancuernas",
  "0293": "remo con torso inclinado con mancuernas",
  "1651": "curl de bíceps en zancada con movimiento de bowling con mancuerna",
  "1652": "curl de bíceps sobre pelota suiza con pierna elevada con mancuerna",
  "1653": "curl de bíceps en apoyo unipodal con mancuerna",
  "0294": "curl de bíceps con mancuernas",
  "2401": "curl de bíceps con mancuernas (con arm blaster)",
  "1654": "curl de bíceps invertido con mancuernas",
  "1655": "curl de bíceps en sentadilla con mancuernas",
  "1656": "curl de bíceps en V-sit sobre bosu con mancuernas",
  "1201": "burpee con mancuernas",
  "0295": "cargada con mancuernas",
  "1731": "press con agarre cerrado con mancuernas",
  "0296": "press con agarre cerrado con mancuernas",
  "0297": "curl concentrado con mancuerna",
  "3635": "zancada adelante contralateral con mancuerna",
  "0298": "curl martillo cruzado con mancuerna",
  "1657": "curl martillo cruzado con mancuerna (v. 2)",
  "0299": "press cubano con mancuernas",
  "2136": "press cubano con mancuernas (v. 2)",
  "0300": "peso muerto con mancuernas",
  "0301": "press de banca declinado con mancuernas",
  "0302": "apertura declinada con mancuernas",
  "0303": "press martillo declinado con mancuernas",
  "1276": "apertura declinada a un brazo con mancuerna",
  "1617": "press martillo declinado a un brazo con mancuerna",
  "0305": "encogimiento de hombros declinado con mancuernas",
  "0304": "encogimiento de hombros declinado con mancuernas (v. 2)",
  "0306": "extensión de tríceps declinada con mancuernas",
  "0307": "apertura declinada con giro con mancuernas",
  "1437": "curl de dedos con mancuernas",
  "0308": "apertura con mancuernas",
  "1277": "apertura sobre pelota suiza con mancuernas",
  "1732": "extensión de tríceps en zancada adelante con mancuernas",
  "0310": "elevación frontal con mancuernas",
  "0309": "elevación frontal con mancuernas (v. 2)",
  "0311": "elevación lateral tipo full can con mancuernas",
  "1760": "sentadilla goblet con mancuerna",
  "0313": "curl martillo con mancuernas",
  "1659": "curl martillo sobre pelota suiza con mancuernas",
  "0312": "curl martillo con mancuernas (v. 2)",
  "2402": "curl martillo con mancuernas (con arm blaster)",
  "1664": "curl alto con mancuernas",
  "3545": "press inclinado alternado con mancuernas",
  "0314": "press de banca inclinado con mancuernas",
  "0315": "curl de bíceps inclinado con mancuernas",
  "0316": "aperturas inclinadas con mancuernas",
  "0318": "curl inclinado con mancuernas",
  "0317": "curl inclinado con mancuernas (v. 2)",
  "0319": "apertura inclinada con mancuernas",
  "1278": "apertura inclinada sobre pelota suiza con mancuernas",
  "0320": "curl martillo inclinado con mancuernas",
  "0321": "press martillo inclinado con mancuernas",
  "1618": "press martillo inclinado sobre pelota suiza con mancuernas",
  "0322": "curl de bíceps interno inclinado con mancuernas",
  "1279": "apertura inclinada a un brazo con mancuerna",
  "1280": "apertura inclinada a un brazo sobre pelota suiza con mancuerna",
  "1619": "press martillo inclinado a un brazo con mancuerna",
  "1620": "press martillo inclinado a un brazo sobre pelota suiza con mancuerna",
  "0323": "elevación lateral inclinada a un brazo con mancuerna",
  "1281": "press inclinado a un brazo con mancuerna",
  "1282": "press inclinado a un brazo sobre pelota suiza con mancuerna",
  "0324": "press inclinado con palmas enfrentadas con mancuernas",
  "1283": "press inclinado sobre pelota suiza con mancuernas",
  "0325": "elevación inclinada con mancuernas",
  "0326": "elevación posterior inclinada con mancuernas",
  "0327": "remo inclinado con mancuernas",
  "0328": "elevación de hombros inclinada con mancuernas",
  "0329": "encogimiento de hombros inclinado con mancuernas",
  "3542": "elevación en T inclinada con mancuernas",
  "0330": "extensión de tríceps inclinada con mancuernas",
  "0331": "aperturas inclinadas con giro con mancuernas",
  "1733": "extensión a dos brazos inclinada con mancuerna",
  "3541": "elevación en Y inclinada con mancuernas",
  "0332": "cruz de hierro con mancuernas",
  "0333": "patada de tríceps con mancuernas",
  "1734": "patadas de tríceps sobre pelota suiza con mancuernas",
  "1660": "curl de bíceps de rodillas sobre pelota suiza con mancuernas",
  "0334": "elevación lateral con mancuernas",
  "0335": "elevación lateral y frontal con mancuernas",
  "0336": "zancada con mancuernas",
  "1658": "zancada con curl de bíceps con mancuernas",
  "0337": "extensión acostado con mancuerna (por delante de la cara)",
  "1729": "extensión alternada acostado con mancuernas",
  "0338": "press de codos acostado con mancuernas",
  "0863": "rotación externa de hombro acostado con mancuerna",
  "0339": "curl femoral acostado con mancuerna",
  "0340": "press martillo acostado con mancuernas",
  "2470": "elevación de deltoides posterior acostado en el piso con mancuernas",
  "0341": "elevación posterior de deltoides a un brazo acostado con mancuerna",
  "0343": "press a un brazo acostado con mancuerna",
  "0342": "press a un brazo acostado con mancuerna (v. 2)",
  "0344": "extensión de tríceps a un brazo pronado acostado con mancuerna",
  "0345": "elevación posterior a un brazo acostado con mancuerna",
  "0346": "extensión de tríceps a un brazo supinado acostado con mancuerna",
  "0347": "pronación acostado con mancuerna",
  "2705": "pronación acostado en el piso con mancuerna",
  "1284": "pullover acostado sobre pelota suiza con mancuerna",
  "1328": "remo para deltoides posterior acostado con mancuernas",
  "0348": "elevación posterior acostado con mancuernas",
  "1735": "extensión individual acostado con mancuerna",
  "0349": "supinación acostado con mancuerna",
  "2706": "supinación acostado en el piso con mancuerna",
  "1661": "curl de bíceps boca arriba acostado con mancuernas",
  "0350": "curl boca arriba acostado con mancuernas",
  "0351": "extensión de tríceps acostado con mancuernas",
  "1662": "curl abierto acostado con mancuernas",
  "0352": "press de banca con agarre neutro con mancuernas",
  "1285": "apertura a un brazo en banco con mancuerna",
  "0292": "remo con torso inclinado a un brazo con mancuerna",
  "1286": "apertura de pecho a un brazo sobre pelota suiza con mancuerna",
  "0353": "curl concentrado a un brazo con mancuerna (sobre pelota suiza)",
  "1287": "press de pecho declinado a un brazo con mancuerna",
  "1288": "apertura a un brazo sobre pelota suiza con mancuerna",
  "1736": "press francés a un brazo sobre pelota suiza con mancuerna",
  "1663": "curl predicador martillo a un brazo con mancuerna",
  "1621": "press martillo a un brazo sobre pelota suiza con mancuerna",
  "1289": "press de pecho inclinado a un brazo con mancuerna",
  "0354": "patada de tríceps a un brazo con mancuerna",
  "0355": "elevación lateral a un brazo con mancuerna",
  "0356": "elevación lateral a un brazo con apoyo con mancuerna",
  "1290": "press a un brazo sobre pelota suiza con mancuerna",
  "1665": "curl a un brazo boca abajo con mancuerna",
  "1666": "curl martillo a un brazo boca abajo con mancuerna",
  "1291": "pullover a un brazo sobre pelota suiza con mancuerna",
  "0358": "curl invertido de muñeca a un brazo con mancuerna",
  "0359": "apertura posterior a un brazo con apoyo con mancuerna",
  "1622": "press con agarre invertido a un brazo con mancuerna",
  "1414": "curl predicador invertido a un brazo con mancuerna",
  "1667": "curl araña invertido a un brazo con mancuerna",
  "1668": "curl de bíceps a un brazo sentado sobre pelota suiza con mancuerna",
  "1669": "curl martillo a un brazo sentado con mancuerna",
  "1415": "curl de muñeca neutro a un brazo sentado con mancuerna",
  "0361": "press de hombros a un brazo con mancuerna",
  "0360": "press de hombros a un brazo con mancuerna (v. 2)",
  "3888": "arranque a un brazo con mancuerna",
  "1670": "curl a un brazo de pie con mancuerna",
  "1671": "curl martillo a un brazo de pie con mancuerna",
  "0362": "extensión de tríceps a un brazo con mancuerna (en banco)",
  "0363": "remo al mentón a un brazo con mancuerna",
  "0364": "curl de muñeca a un brazo con mancuerna",
  "1672": "curl predicador zottman a un brazo con mancuerna",
  "1292": "apertura a una pierna sobre pelota suiza con mancuerna",
  "0365": "curl de muñeca neutro sobre banco con mancuerna",
  "0366": "curl de muñeca neutro a un brazo sobre banco con mancuerna",
  "1441": "curl invertido de muñeca a un brazo sobre banco con mancuerna",
  "0367": "curl de muñeca a un brazo sobre banco con mancuerna",
  "0368": "curl invertido de muñeca sobre banco con mancuerna",
  "0369": "curl de muñeca sobre banco con mancuerna",
  "1329": "remo con torso inclinado y rotación de muñeca con mancuernas",
  "1623": "press de banca inclinado con palmas enfrentadas con mancuernas",
  "0370": "curl predicador martillo con mancuerna",
  "0371": "sentadilla pliométrica con mancuernas",
  "0372": "curl predicador con mancuernas",
  "1673": "curl predicador sobre pelota suiza con mancuernas",
  "1293": "press sobre pelota suiza con mancuernas",
  "0373": "extensión de tríceps con agarre pronado con mancuernas",
  "0374": "curl inclinado boca abajo con mancuernas",
  "1674": "curl martillo inclinado boca abajo con mancuernas",
  "0375": "pullover con mancuerna",
  "1294": "pullover con extensión de cadera sobre pelota suiza con mancuerna",
  "1295": "pullover sobre pelota suiza con mancuerna",
  "1700": "push press con mancuernas",
  "0376": "elevación con mancuernas",
  "2292": "elevación de deltoides posterior con mancuernas",
  "0377": "remo para deltoides posterior con mancuernas",
  "0378": "apertura posterior con mancuernas",
  "0380": "elevación posterior con mancuernas",
  "0379": "elevación posterior con mancuernas (cabeza apoyada)",
  "0381": "zancada hacia atrás con mancuernas",
  "0382": "curl de bíceps con agarre invertido con mancuernas",
  "1624": "press de banca invertido con mancuernas",
  "0383": "apertura posterior con mancuernas",
  "1330": "remo a un brazo en banco inclinado con agarre invertido con mancuerna",
  "1331": "remo a dos brazos en banco inclinado con agarre invertido con mancuernas",
  "2327": "remo con agarre invertido con mancuernas",
  "0384": "curl predicador invertido con mancuernas",
  "1675": "curl araña invertido con mancuernas",
  "0385": "curl invertido de muñeca con mancuernas",
  "1459": "peso muerto rumano con mancuernas",
  "0386": "apertura posterior con rotación con mancuernas",
  "2397": "press scott con mancuernas",
  "0387": "elevación frontal alternada sentado con mancuernas",
  "1676": "curl martillo alternado sentado sobre pelota suiza con mancuernas",
  "0388": "press alternado sentado con mancuernas",
  "3546": "press de hombros alternado sentado con mancuernas",
  "0389": "extensión sentado en banco con mancuernas",
  "2317": "elevación lateral con brazos flexionados sentado con mancuernas",
  "1730": "patada de tríceps alternada con torso inclinado sentado con mancuernas",
  "1737": "extensión de tríceps con torso inclinado sentado con mancuernas",
  "1677": "curl de bíceps sentado con mancuernas",
  "0390": "curl de bíceps sentado con mancuernas (sobre pelota suiza)",
  "3547": "curl de bíceps al press de hombros sentado con mancuernas",
  "1379": "elevación de gemelos sentado con mancuernas",
  "0391": "curl sentado con mancuernas",
  "0392": "elevación frontal sentado con mancuernas",
  "1678": "curl martillo sentado con mancuernas",
  "0393": "curl de bíceps interno sentado con mancuernas",
  "0394": "patada de tríceps sentado con mancuernas",
  "0396": "elevación lateral sentado con mancuernas",
  "0395": "elevación lateral sentado con mancuernas (v. 2)",
  "0397": "curl de muñeca neutro sentado con mancuernas",
  "1679": "curl de bíceps a un brazo sentado sobre pelota suiza con pierna elevada con mancuerna",
  "0398": "patada de tríceps a un brazo sentado con mancuerna",
  "0399": "rotación a un brazo sentado con mancuerna",
  "0400": "elevación de gemelo a una pierna sentado con mancuerna",
  "1380": "elevación de gemelo a una pierna sentado con mancuerna (agarre martillo)",
  "1381": "elevación de gemelo a una pierna sentado con mancuerna (palma arriba)",
  "0401": "curl de muñeca con palmas arriba sentado con mancuernas",
  "0402": "curl predicador sentado con mancuernas",
  "0403": "curl concentrado con agarre invertido sentado con mancuerna",
  "1738": "extensión de tríceps por encima de la cabeza a un brazo con agarre invertido sentado con mancuerna",
  "0405": "press de hombros sentado con mancuernas",
  "0404": "press de hombros sentado con mancuernas (agarre paralelo)",
  "2188": "extensión de tríceps sentado con mancuerna",
  "0406": "encogimiento de hombros con mancuernas",
  "0407": "flexión lateral de tronco con mancuerna",
  "0408": "elevación a una mano de costado con mancuerna",
  "3664": "plancha lateral con apertura posterior con mancuerna",
  "3548": "traslado por encima de la cabeza a un brazo con mancuerna",
  "0409": "elevación de gemelo a una pierna con mancuerna",
  "1757": "peso muerto a una pierna con mancuerna",
  "2805": "peso muerto a una pierna con apoyo en cajón con mancuerna",
  "0410": "sentadilla búlgara a una pierna con mancuernas",
  "0411": "sentadilla a una pierna con mancuerna",
  "0413": "sentadilla con mancuernas",
  "3560": "curl martillo alternado y press de pie con mancuernas",
  "0414": "press alternado por encima de la cabeza de pie con mancuernas",
  "0415": "elevación alternada de pie con mancuernas",
  "1739": "patada de tríceps alternada de pie con mancuernas",
  "2143": "círculos alrededor del cuerpo de pie con mancuerna",
  "1740": "extensión de tríceps a un brazo con torso inclinado de pie con mancuerna",
  "1741": "extensión de tríceps a dos brazos con torso inclinado de pie con mancuernas",
  "0416": "curl de bíceps de pie con mancuernas",
  "0417": "elevación de gemelos de pie con mancuernas",
  "0418": "curl concentrado de pie con mancuerna",
  "0419": "elevación frontal por encima de la cabeza de pie con mancuernas",
  "2321": "curl de bíceps interno de pie con mancuernas (v. 2)",
  "0420": "patada de tríceps de pie con mancuernas",
  "0421": "curl concentrado a un brazo de pie con mancuerna",
  "0422": "curl a un brazo de pie con mancuerna (sobre banco inclinado)",
  "1680": "curl a un brazo de pie sobre banco inclinado con mancuerna",
  "0423": "extensión a un brazo de pie con mancuerna",
  "0424": "press a un brazo con palma adentro de pie con mancuerna",
  "0425": "curl invertido a un brazo de pie con mancuerna",
  "0426": "press por encima de la cabeza de pie con mancuernas",
  "0427": "press con palmas enfrentadas de pie con mancuernas",
  "0428": "curl predicador de pie con mancuernas",
  "0429": "curl invertido de pie con mancuernas",
  "0430": "extensión de tríceps de pie con mancuernas",
  "2293": "curl predicador zottman de pie con mancuernas",
  "1684": "subida al cajón con equilibrio a una pierna y curl de bíceps con mancuernas",
  "0431": "subida al cajón con mancuernas",
  "2796": "subida al cajón con zancada con mancuernas",
  "2812": "subida al cajón con sentadilla búlgara con mancuernas",
  "0432": "peso muerto con piernas rígidas con mancuernas",
  "0433": "pullover con brazos rectos con mancuerna",
  "0434": "peso muerto con piernas rectas con mancuernas",
  "2808": "pull through sumo con mancuerna",
  "2803": "sentadilla con apoyo con mancuernas",
  "0436": "press tate con mancuernas",
  "1742": "patada de tríceps en apoyo unipodal con mancuerna",
  "1743": "press de banca con giro con mancuernas",
  "0437": "remo al mentón con mancuernas",
  "1765": "remo al mentón con mancuernas (vista posterior)",
  "0864": "rotación externa de hombro al mentón con mancuerna",
  "5201": "curl de bíceps tipo mozo con mancuerna",
  "0438": "press en W con mancuernas",
  "0439": "curl zottman con mancuernas",
  "2294": "curl predicador zottman con mancuernas",
  "2189": "extensión de tríceps sentado con mancuernas",
  "1167": "estiramiento dinámico de pecho",
  "3287": "fondos de codos",
  "1772": "elevación de codos - flexión invertida",
  "0443": "codo a rodilla",
  "3292": "ascensor",
  "1332": "elevaciones de brazos alternadas sobre pelota suiza",
  "1333": "extensión de espalda con brazos extendidos sobre pelota suiza",
  "1334": "extensión de espalda con manos tras nuca sobre pelota suiza",
  "1335": "extensión de espalda con rodillas sin apoyo sobre pelota suiza",
  "1336": "extensión de espalda con rotación sobre pelota suiza",
  "1744": "fondo sobre pelota suiza",
  "1559": "estiramiento de flexor de cadera sobre pelota suiza",
  "1338": "abrazo sobre pelota suiza",
  "1339": "estiramiento de dorsal sobre pelota suiza",
  "1341": "estiramiento de zona lumbar sobre pelota suiza (pirámide)",
  "1342": "estiramiento lateral de dorsal acostado sobre pelota suiza",
  "1382": "elevación de gemelos contra la pared sobre pelota suiza",
  "3241": "elevación de gemelos contra la pared sobre pelota suiza (pelota de tenis entre los tobillos)",
  "3240": "elevación de gemelos contra la pared sobre pelota suiza (pelota de tenis entre las rodillas)",
  "1416": "rotación del tren inferior a una pierna boca abajo sobre pelota suiza",
  "1417": "curl femoral con patada diagonal a una pierna sobre pelota suiza",
  "1296": "flexión pike sobre pelota suiza",
  "1343": "elevación de piernas boca abajo sobre pelota suiza",
  "1560": "estiramiento de femorales sentado sobre pelota suiza",
  "1745": "estiramiento de tríceps sentado sobre pelota suiza",
  "1746": "extensión de tríceps boca arriba sobre pelota suiza",
  "1747": "press francés sobre pelota suiza con barra Z",
  "3010": "pullover acostado con brazos flexionados con barra Z",
  "1748": "extensión de tríceps acostado con agarre cerrado tras nuca con barra Z",
  "1344": "remo con torso inclinado con agarre invertido con barra Z",
  "1682": "curl concentrado sentado con agarre cerrado con barra Z",
  "1749": "press francés de pie con barra Z",
  "0445": "press antigravedad con barra Z",
  "1627": "curl predicador con agarre cerrado con barra Z",
  "0446": "curl con agarre cerrado con barra Z",
  "0447": "curl con barra Z",
  "0448": "press hacia la cara declinado con agarre cerrado con barra Z",
  "2186": "extensión de tríceps declinada con barra Z",
  "0449": "extensión de tríceps inclinada con barra Z",
  "0450": "press de banca JM con barra Z",
  "0451": "curl con agarre invertido con barra Z",
  "0452": "curl predicador con agarre invertido con barra Z",
  "1458": "curls sentado con barra Z",
  "0453": "extensión de tríceps sentado con barra Z",
  "0454": "curl araña con barra Z",
  "1628": "curl araña con barra Z",
  "2404": "curl de bíceps con barra Z (con arm blaster)",
  "2432": "press de banca con agarre cerrado con barra Z",
  "2741": "curl de bíceps con agarre abierto de pie con barra Z",
  "2133": "caminata del granjero",
  "0455": "curl de dedos",
  "3303": "la bandera",
  "0456": "abdominal con piernas flexionadas (rodilla flexionada)",
  "0457": "abdominal con piernas flexionadas (brazo recto)",
  "0458": "apertura en el piso (con barra)",
  "0459": "patadas de tijera",
  "1472": "salto hacia adelante",
  "3470": "zancada hacia adelante",
  "3194": "sentadilla frankenstein",
  "2429": "crunch rana",
  "3301": "planche rana",
  "3296": "front lever",
  "3295": "repeticiones de front lever",
  "0464": "plancha frontal con giro",
  "3315": "maltés completo",
  "3299": "planche completo",
  "3327": "flexión en planche completo",
  "0466": "dominada al esternón de gironda",
  "3561": "marcha en puente de glúteos",
  "3523": "puente de glúteos con ambas piernas en banco",
  "3193": "elevación glúteo-femoral",
  "0467": "dominada de gorila",
  "0469": "crunch de ingle",
  "1383": "elevación de gemelos en hack",
  "1384": "elevación de gemelo a una pierna en hack",
  "3221": "medias flexiones de rodilla",
  "3202": "medio abdominal",
  "1511": "estiramiento de femorales",
  "2139": "bicicleta de brazos",
  "3218": "toque de punta de pie en círculo con manos entrelazadas",
  "3215": "toque de punta de pie en círculo con manos entrelazadas al revés",
  "3302": "parada de manos",
  "0471": "flexión en parada de manos",
  "1764": "elevación de cadera y piernas colgado",
  "0472": "elevación de piernas colgado",
  "1761": "elevación oblicua de rodillas colgado",
  "0473": "pike colgado",
  "0474": "elevación de cadera con piernas rectas colgado",
  "0475": "elevación de piernas rectas colgado",
  "0476": "elevación de cadera con piernas rectas y giro colgado",
  "3636": "rodilla alta contra la pared",
  "0484": "elevación de cadera (rodilla flexionada)",
  "1418": "abrazo de rodillas al pecho",
  "3234": "apertura hyght con mancuernas",
  "0489": "hiperextensión",
  "0488": "hiperextensión (en banco)",
  "3289": "fondos imposibles",
  "1471": "gusano (inchworm)",
  "3698": "gusano (inchworm) (v. 2)",
  "0490": "flexión inclinada con agarre cerrado",
  "0491": "elevación de cadera con pierna inclinada (pierna recta)",
  "0492": "flexión inclinada con salto en profundidad",
  "0493": "flexión inclinada",
  "3785": "flexión inclinada (sobre cajón)",
  "0494": "flexión inclinada con agarre invertido",
  "3011": "flexión escapular inclinada",
  "0495": "abdominal inclinado con giro",
  "1564": "estiramiento intermedio de flexor de cadera y cuádriceps",
  "0496": "curl femoral invertido (apoyo en banco)",
  "2400": "curl femoral invertido (en máquina de dominadas)",
  "0499": "remo invertido",
  "2300": "remo invertido con rodillas flexionadas",
  "2298": "remo invertido en banco",
  "0497": "remo invertido (v. 2)",
  "0498": "remo invertido con correas",
  "1419": "estiramiento cruz de hierro",
  "1297": "compresión isométrica de pecho",
  "0500": "limpiaparabrisas isométrico",
  "0501": "burpee con salto de tijera",
  "3224": "salto de tijera (jack jump)",
  "0507": "abdominal navaja",
  "0508": "abdominal janda",
  "2612": "saltar la cuerda",
  "0514": "sentadilla con salto",
  "0513": "sentadilla con salto (v. 2)",
  "0517": "molino de viento avanzado con kettlebell",
  "0518": "cargada colgante alternada con kettlebell",
  "0520": "press alternado con kettlebell",
  "0519": "press alternado en el piso con kettlebell",
  "0521": "remo renegado alternado con kettlebell",
  "0522": "remo alternado con kettlebell",
  "0523": "press arnold con kettlebell",
  "0524": "press inclinado (bent press) con kettlebell",
  "0525": "cargada bottoms-up desde posición colgante con kettlebell",
  "0526": "cargada colgante alternada doble con kettlebell",
  "0527": "envión doble con kettlebell",
  "0528": "push press doble con kettlebell",
  "0529": "arranque doble con kettlebell",
  "0530": "molino de viento doble con kettlebell",
  "0531": "press a un brazo con rango extendido en el piso con kettlebell",
  "0532": "figura 8 con kettlebell",
  "0533": "sentadilla frontal con kettlebell",
  "0534": "sentadilla goblet con kettlebell",
  "0535": "cargada colgante con kettlebell",
  "0536": "zancada con pase por debajo con kettlebell",
  "0537": "cargada y envión a un brazo con kettlebell",
  "1298": "press en el piso a un brazo con kettlebell",
  "0538": "envión a un brazo con kettlebell",
  "0539": "press militar a un brazo hacia el costado con kettlebell",
  "0540": "push press a un brazo con kettlebell",
  "0541": "remo a un brazo con kettlebell",
  "0542": "arranque a un brazo con kettlebell",
  "0543": "piernas de pirata con kettlebell",
  "0544": "sentadilla pistol con kettlebell",
  "0545": "flexión pliométrica con kettlebell",
  "0546": "press sentado con kettlebell",
  "1438": "press militar a dos brazos sentado con kettlebell",
  "0547": "press tipo balancín con kettlebell",
  "0548": "tirón alto sumo con kettlebell",
  "0549": "swing con kettlebell",
  "0550": "thruster con kettlebell",
  "0551": "turkish get-up con kettlebell (estilo sentadilla)",
  "0552": "cargada a dos brazos con kettlebell",
  "0553": "press militar a dos brazos con kettlebell",
  "1345": "remo a dos brazos con kettlebell",
  "0554": "molino de viento con kettlebell",
  "0555": "kick out sit",
  "0558": "muscle up con kipping",
  "3640": "crunch con toque a la rodilla",
  "1420": "sentadilla con salto de rodillas",
  "1346": "estiramiento de dorsal de rodillas",
  "3239": "plancha de rodillas con toque al hombro",
  "3211": "flexión de rodillas",
  "3288": "fondos coreanos",
  "3418": "dominada en L",
  "3419": "L-sit en el piso",
  "0562": "landmine 180",
  "3237": "elevación lateral con landmine",
  "3300": "planche inclinado",
  "2271": "gancho de izquierda (boxeo)",
  "0570": "elevación de piernas al pecho en banco plano",
  "1576": "estiramiento de femorales con pierna elevada",
  "2287": "prensa de piernas alternada en máquina",
  "0571": "remo sentado alternado con agarre cerrado en máquina",
  "0572": "dominada supina asistida en máquina",
  "0573": "extensión de espalda en máquina",
  "0574": "remo con torso inclinado en máquina",
  "3200": "remo con torso inclinado con barra en V en máquina",
  "0575": "curl de bíceps en máquina",
  "2289": "prensa de gemelos en máquina",
  "0577": "press de pecho en máquina",
  "0576": "press de pecho en máquina",
  "0578": "peso muerto en máquina",
  "1300": "press de pecho declinado en máquina",
  "1253": "elevación de gemelos tipo burro en máquina",
  "0579": "jalón al pecho frontal en máquina",
  "0580": "encogimiento de hombros sin agarre en máquina",
  "1439": "encogimiento de hombros sin agarre en máquina (v. 2)",
  "2288": "cierre de manos en máquina",
  "1615": "curl predicador con agarre martillo en máquina",
  "0581": "remo alto en máquina",
  "2286": "extensión de cadera en máquina (v. 2)",
  "2611": "prensa de piernas horizontal a una pierna en máquina",
  "1299": "press de pecho inclinado en máquina",
  "1479": "press de pecho inclinado en máquina (v. 2)",
  "0582": "curl femoral de rodillas en máquina",
  "0583": "giro de rodillas en máquina",
  "0584": "elevación lateral en máquina",
  "0585": "extensión de cuádriceps en máquina",
  "0586": "curl femoral acostado en máquina",
  "3195": "curl femoral acostado de dos a una pierna en máquina",
  "0587": "press militar en máquina",
  "0588": "remo sentado con agarre cerrado en máquina",
  "0589": "remo con torso inclinado a un brazo en máquina",
  "1356": "remo alto lateral a un brazo en máquina",
  "1347": "jalón lateral abierto a un brazo en máquina",
  "0590": "press de hombros a un brazo en máquina",
  "0591": "fondo de tríceps con agarre prono en máquina",
  "0592": "curl predicador en máquina",
  "1614": "curl predicador en máquina (v. 2)",
  "2285": "pullover en máquina",
  "2736": "jalón al pecho con agarre invertido en máquina",
  "1616": "curl predicador con agarre invertido en máquina",
  "1348": "remo vertical con agarre invertido en máquina",
  "0593": "hiperextensión invertida en máquina",
  "1349": "remo en punta invertido en máquina",
  "2315": "gemelo rotatorio en máquina",
  "2335": "prensa de gemelos sentado en máquina",
  "0594": "elevación de gemelos sentado en máquina",
  "1452": "crunch sentado en máquina",
  "0595": "crunch sentado en máquina (apoyo en el pecho)",
  "3760": "crunch sentado en máquina (v. 2)",
  "1451": "fondo sentado en máquina",
  "0596": "apertura sentado en máquina",
  "3759": "buenos días sentado en máquina",
  "0597": "abducción de cadera sentado en máquina",
  "0598": "aducción de cadera sentado en máquina",
  "0599": "curl femoral sentado en máquina",
  "0600": "crunch con elevación de piernas sentado en máquina",
  "0602": "apertura posterior sentado en máquina",
  "0601": "apertura posterior sentado en máquina (agarre paralelo)",
  "1350": "remo sentado en máquina",
  "1385": "elevación de gemelos en sentadilla sentado en la prensa de piernas",
  "0603": "press de hombros en máquina",
  "0869": "press de hombros en máquina (v. 2)",
  "2318": "press de hombros en máquina (v. 3)",
  "0604": "encogimiento de hombros en máquina",
  "0605": "elevación de gemelos de pie en máquina",
  "3758": "press de pecho de pie en máquina",
  "0606": "remo en punta en máquina",
  "1351": "remo en punta con agarre invertido en máquina",
  "0607": "extensión de tríceps en máquina",
  "1313": "remo unilateral en máquina",
  "0609": "puente de londres",
  "3013": "puente de glúteos bajo en el piso",
  "1352": "curl de zona lumbar",
  "3582": "zancada con salto",
  "1688": "zancada con giro",
  "0613": "estiramiento de cuádriceps acostado (de costado)",
  "2312": "codo a rodilla acostado",
  "0620": "elevación de piernas acostado en banco plano",
  "0865": "elevación de piernas y cadera acostado",
  "1301": "press de pecho interno en máquina",
  "0624": "sentadilla isométrica en la pared con marcha",
  "1353": "recepción y lanzamiento por encima de la cabeza con balón medicinal",
  "1302": "pase de pecho con balón medicinal",
  "1303": "empuje de pecho desde posición de 3 apoyos con balón medicinal",
  "1304": "empuje de pecho de respuesta múltiple con balón medicinal",
  "1305": "empuje de pecho de respuesta única con balón medicinal",
  "1312": "empuje de pecho con carrera de liberación con balón medicinal",
  "1701": "flexión con agarre cerrado con balón medicinal",
  "1354": "golpe por encima de la cabeza con balón medicinal",
  "1750": "lanzamiento de pecho boca arriba con balón medicinal",
  "0627": "dominada supina con agarre mixto",
  "3217": "flexión hindú modificada",
  "1421": "flexión modificada bajando a los antebrazos",
  "0628": "caminata del monstruo",
  "0630": "escalador",
  "0631": "muscle up",
  "1401": "muscle up (en barra vertical)",
  "2328": "flexión cerrada sobre pelota suiza",
  "1403": "estiramiento lateral de cuello",
  "0634": "crunch negativo",
  "1495": "crunch oblicuo (v. 2)",
  "0635": "crunches oblicuos en el piso",
  "0636": "curl martillo con barra olímpica",
  "0637": "extensión de tríceps con barra olímpica",
  "1355": "un brazo contra la pared",
  "0638": "dominada supina a un brazo",
  "0639": "fondo a un brazo",
  "0640": "golpe a un brazo (con balón medicinal)",
  "1773": "remo a un brazo con toalla",
  "1386": "elevación de gemelo tipo burro a una pierna",
  "1387": "elevación de gemelo en el piso a una pierna",
  "1476": "sentadilla a una pierna",
  "0641": "otis up",
  "0642": "flexión con patada de pierna hacia afuera",
  "0643": "estiramiento de tríceps por encima de la cabeza",
  "3147": "báscula pélvica",
  "1422": "báscula pélvica a puente",
  "1388": "estiramiento de peroneos",
  "3662": "flexión de pike a cobra",
  "1306": "flexión pliométrica",
  "1687": "paso hacia atrás con alcance por encima de la cabeza",
  "1389": "estiramiento de tibial posterior",
  "3119": "sentadilla profunda tipo potty",
  "3132": "sentadilla profunda tipo potty con apoyo",
  "0648": "cargada de potencia",
  "3665": "plancha power point",
  "3203": "medio abdominal de prisionero",
  "1707": "giro boca abajo sobre pelota suiza",
  "0651": "dominada (agarre neutro)",
  "0650": "pull-in (sobre pelota suiza)",
  "0652": "dominada",
  "1689": "empujar y traccionar con peso corporal",
  "3638": "de flexión a carrera",
  "1307": "flexión sobre bosu",
  "0662": "flexión de brazos",
  "0653": "flexión (bosu)",
  "0655": "flexión (sobre pelota suiza)",
  "0656": "flexión (sobre pelota suiza)",
  "0659": "flexión (pared)",
  "0658": "flexión (pared) (v. 2)",
  "0660": "flexión con agarre cerrado sobre mancuernas",
  "0661": "flexión con patada de pierna hacia adentro",
  "0663": "flexión sobre balón medicinal",
  "1467": "flexión sobre los antebrazos",
  "3145": "flexión plus",
  "0664": "flexión a plancha lateral",
  "3533": "cuádriceps",
  "3201": "cuarto de abdominal",
  "3552": "pies rápidos (v. 2)",
  "0666": "flexión con elevación de un brazo",
  "0668": "puente declinado posterior",
  "0669": "estiramiento de deltoides posterior",
  "0670": "dominada posterior",
  "1582": "postura del dedo gordo reclinada con soga",
  "3236": "empujes de cadera de rodillas con banda elástica",
  "3007": "extensión de cuádriceps con banda elástica",
  "3123": "curl de bíceps sentado con banda elástica",
  "3124": "press de pecho sentado con banda elástica",
  "3006": "abducción de cadera sentado con banda elástica",
  "3122": "press de hombros sentado con banda elástica",
  "3144": "remo sentado con espalda recta con banda elástica",
  "0872": "crunch invertido",
  "0672": "fondo invertido",
  "0673": "jalón al pecho con agarre invertido en máquina",
  "0674": "dominada con agarre invertido",
  "0675": "hiperextensión invertida (sobre pelota suiza)",
  "1423": "hiperextensión invertida en banco plano",
  "3663": "plancha invertida con elevación de pierna",
  "0677": "fondos en anillas",
  "2571": "estiramiento de rana con balanceo",
  "0678": "dominada a jalón rocky",
  "2208": "estiramiento de espalda con rodillo",
  "2204": "body saw con rodillo",
  "2205": "estiramiento de cadera y dorsal con rodillo",
  "2202": "estiramiento de cadera con rodillo",
  "2206": "crunch invertido con rodillo",
  "2203": "movilidad de hombros sentado con rodillo",
  "2209": "movilidad de hombros a una pierna sentado con rodillo",
  "2207": "estiramiento lateral de dorsal con rodillo",
  "0680": "trepa de cuerda",
  "0685": "correr",
  "0684": "correr (equipo)",
  "1585": "estiramiento del corredor",
  "0687": "giro ruso",
  "3012": "fondos escapulares",
  "3021": "flexión escapular",
  "0688": "dominada escapular",
  "3219": "saltos de tijera",
  "1390": "estiramiento de gemelos sentado",
  "1424": "estiramiento de glúteos sentado",
  "0689": "elevación de piernas sentado",
  "0690": "estiramiento de zona lumbar sentado",
  "2567": "estiramiento de piriforme sentado",
  "0691": "crunch lateral sentado (pared)",
  "1587": "secuencia de postura de ángulo abierto sentado",
  "0697": "curl femoral invertido autoasistido",
  "1766": "curl femoral invertido autoasistido",
  "0696": "curl femoral invertido autoasistido (en el piso)",
  "3222": "salto en media sentadilla",
  "3656": "carrera de zancada corta",
  "1763": "dominada con agarre a la altura de los hombros",
  "3699": "toque al hombro",
  "0699": "flexión con toque al hombro",
  "1774": "abducción de cadera en plancha lateral",
  "0705": "plancha lateral (v. 2)",
  "0709": "elevación de cadera lateral (en paralelas)",
  "0710": "abducción de cadera lateral",
  "1358": "estiramiento en el piso de costado",
  "3667": "aducción de cadera acostado de costado",
  "1775": "aducción de cadera en plancha lateral",
  "0716": "estiramiento de cuello con empuje lateral",
  "0717": "flexión lateral",
  "0721": "estiramiento de muñeca con tracción lateral",
  "0720": "dominada de lado a lado",
  "3213": "toque de punta de pie de lado a lado",
  "0725": "flexión a un brazo",
  "3645": "puente a una pierna con pierna extendida",
  "0727": "elevación de gemelo a una pierna (sobre una mancuerna)",
  "0730": "deslizamiento en plataforma a una pierna",
  "1759": "sentadilla a una pierna (pistol)",
  "1489": "sentadilla sissy",
  "0735": "abdominal (v. 2)",
  "3679": "abdominal con brazos sobre el pecho",
  "3361": "saltos de patinador",
  "2142": "ergómetro de esquí",
  "3671": "paso de esquí",
  "3304": "skin the cat",
  "1425": "prensa de piernas a 45° a una pierna",
  "0738": "prensa de gemelos a 45°",
  "0739": "prensa de piernas a 45°",
  "1464": "prensa de piernas a 45° (vista posterior)",
  "1463": "prensa de piernas a 45° (vista lateral)",
  "0740": "prensa de piernas abierta a 45°",
  "1391": "prensa de gemelos en la prensa de piernas",
  "0741": "hack squat con pies juntos en prensa",
  "0742": "elevación de gemelos con ángulo hacia adelante en prensa",
  "0743": "hack squat en prensa",
  "2334": "prensa de gemelos acostado en prensa",
  "0744": "sentadilla acostado en prensa",
  "1392": "prensa de gemelos a una pierna en la prensa de piernas",
  "1496": "martillo de trineo",
  "0746": "encogimiento de hombros por detrás en multipower",
  "0747": "press tras nuca en multipower",
  "0748": "press de banca en multipower",
  "0749": "buenos días con rodillas flexionadas en multipower",
  "1359": "remo con torso inclinado en multipower",
  "0750": "sentadilla en silla en multipower",
  "0751": "press de banca con agarre cerrado en multipower",
  "0752": "peso muerto en multipower",
  "0753": "press de banca declinado en multipower",
  "0754": "press declinado con agarre invertido en multipower",
  "1433": "sentadilla frontal en multipower (agarre de cargada)",
  "3281": "sentadilla profunda en multipower",
  "0755": "hack squat en multipower",
  "0756": "elevación de cadera en multipower",
  "0757": "press de banca inclinado en multipower",
  "0758": "press inclinado con agarre invertido en multipower",
  "0759": "elevaciones de hombros inclinado en multipower",
  "0760": "prensa de piernas en multipower",
  "1434": "sentadilla con barra baja en multipower",
  "1683": "curl de bíceps en multipower",
  "1625": "press de banca declinado con agarre cerrado en multipower",
  "1752": "extensión de tríceps inclinada en multipower",
  "1626": "press de banca declinado invertido con agarre cerrado en multipower",
  "0761": "remo cerrado en multipower",
  "1360": "remo a un brazo en multipower",
  "1393": "elevación de gemelo en el piso a una pierna en multipower",
  "0762": "remo para deltoides posterior en multipower",
  "0763": "elevaciones de gemelos invertidas en multipower",
  "1394": "elevaciones de gemelos invertidas en multipower",
  "1361": "remo con torso inclinado con agarre invertido en multipower",
  "0764": "press con agarre invertido en multipower",
  "1395": "elevación de gemelo a una pierna sentado en multipower",
  "0765": "press de hombros sentado en multipower",
  "1426": "curl de muñeca sentado en multipower",
  "0766": "press de hombros en multipower",
  "0767": "encogimiento de hombros en multipower",
  "0768": "sentadilla búlgara a una pierna en multipower",
  "0769": "zancada de sprint en multipower",
  "0770": "sentadilla en multipower",
  "0771": "curl de muñeca por detrás de pie en multipower",
  "0772": "press militar tras nuca de pie en multipower",
  "0773": "elevación de gemelos de pie en multipower",
  "0774": "press militar de pie en multipower",
  "3142": "sentadilla sumo en multipower",
  "1396": "elevación de puntas de pie en multipower",
  "0775": "remo al mentón en multipower",
  "1308": "press de banca con agarre abierto en multipower",
  "1309": "press de banca declinado con agarre abierto en multipower",
  "0776": "tirón de arranque",
  "0777": "spell caster",
  "1362": "esfinge",
  "0778": "flexión con reptado de araña",
  "1363": "estiramiento de columna",
  "2329": "giro de columna",
  "2368": "sentadillas búlgaras",
  "0786": "envión en sentadilla",
  "1705": "sentadilla sobre bosu",
  "1685": "sentadilla con alcance por encima de la cabeza",
  "1686": "sentadilla con alcance por encima de la cabeza y giro",
  "2297": "crunch sobre pelota suiza (rango completo, manos tras nuca)",
  "3291": "stalder press",
  "3669": "arquero de pie",
  "0788": "press tras nuca de pie",
  "1490": "elevación de gemelos de pie (en una escalera)",
  "1397": "gemelos de pie",
  "1398": "estiramiento de gemelos de pie",
  "1599": "estiramiento de femorales y gemelos de pie con banda",
  "0794": "estiramiento lateral de pie",
  "1364": "báscula pélvica de pie",
  "0795": "curl femoral a una pierna de pie",
  "0796": "rueda abdominal de pie",
  "3223": "salto de estrella",
  "2138": "carrera en bicicleta fija (v. 3)",
  "0798": "caminata en bicicleta fija",
  "3314": "maltés con piernas abiertas",
  "3298": "planche con piernas abiertas",
  "1427": "abductor externo de cadera con pierna recta",
  "0803": "flexión superman",
  "0805": "caída abdominal en suspensión",
  "0806": "flexión en suspensión",
  "0807": "crunch invertido en suspensión",
  "0808": "remo en suspensión",
  "0809": "sentadilla búlgara en suspensión",
  "3433": "patadas de nadador (v. 2)",
  "3318": "swing 360",
  "1753": "fondo entre tres bancos",
  "2459": "volteo de neumático",
  "0811": "peso muerto con barra hexagonal",
  "0814": "fondo de tríceps",
  "0812": "fondo de tríceps (pierna en el banco)",
  "0813": "fondo de tríceps (entre bancos)",
  "0815": "fondos de tríceps en el piso",
  "0816": "press de tríceps",
  "0817": "estiramiento de tríceps",
  "0871": "crunch con rodillas al pecho",
  "0818": "jalón al pecho con doble maneral de agarre paralelo",
  "1466": "elevación de cadera con giro",
  "2802": "elevación de piernas con giro",
  "2801": "elevación de piernas con giro",
  "3231": "toque de dos puntas de pie",
  "1365": "estiramiento de espalda alta",
  "1366": "perro boca arriba",
  "3420": "V-sit en el piso",
  "0826": "elevación vertical de piernas (en paralelas)",
  "2141": "caminar en elíptica",
  "3655": "zancada con rodillas altas caminando",
  "1460": "zancada caminando",
  "3666": "caminar en cinta inclinada",
  "2311": "caminar en escaladora",
  "0830": "fondo en banco con lastre",
  "2987": "dominada supina con agarre cerrado y lastre en jaula de fondos",
  "3643": "sentadillas cosaco con lastre",
  "0832": "crunch con lastre",
  "3670": "abdominal declinado con lastre",
  "0833": "elevación de gemelos tipo burro con lastre",
  "1310": "flexión en caída con lastre",
  "2135": "plancha frontal con lastre",
  "0834": "elevación frontal con lastre",
  "0866": "elevación de piernas y cadera colgado con lastre",
  "0835": "hiperextensión con lastre (sobre pelota suiza)",
  "3641": "paso de rodillas con balanceo y lastre",
  "3644": "zancada con balanceo y lastre",
  "3286": "muscle up con lastre",
  "3312": "muscle up con lastre (en barra)",
  "3290": "dominada a una mano con lastre",
  "0840": "crunch por encima de la cabeza con lastre (sobre pelota suiza)",
  "0841": "dominada con lastre",
  "0844": "brazo circular con lastre",
  "0846": "giro ruso con lastre",
  "0845": "giro ruso con lastre (piernas arriba)",
  "2371": "giro ruso con lastre (v. 2)",
  "0847": "curl de bíceps sentado con lastre (sobre pelota suiza)",
  "0849": "giro sentado con lastre (sobre pelota suiza)",
  "0850": "flexión lateral de tronco con lastre (sobre pelota suiza)",
  "0851": "sentadilla sissy con lastre",
  "0852": "sentadilla con lastre",
  "0853": "curl de pie con lastre",
  "0854": "apretón de mano de pie con lastre",
  "3313": "fondo en barra recta con lastre",
  "3642": "zancada con estiramiento y lastre",
  "0856": "press svend con lastre",
  "1754": "fondos entre tres bancos con lastre",
  "1755": "fondos de tríceps con lastre",
  "1767": "fondo de tríceps en paralelas altas con lastre",
  "0857": "rueda abdominal",
  "3637": "carrera con rueda",
  "1429": "dominada con agarre abierto",
  "1367": "dominada posterior con agarre abierto",
  "1311": "flexión con manos abiertas",
  "2363": "fondo de pecho en paralelas altas con agarre abierto",
  "0858": "sprints cortos",
  "1604": "el mejor estiramiento del mundo",
  "1428": "círculos de muñeca",
  "0859": "enrollador de muñeca",
}
